# Generated by Django 5.1.5 on 2025-01-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model3d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='thumbnail',
            field=models.URLField(default='models/TestImage.png'),
            preserve_default=False,
        ),
    ]
